{-
Copyright 2019 Adobe. All rights reserved. This file is licensed to you under
the Apache License, Version 2.0 (the "License"); you may not use this file
except in compliance with the License. You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software distributed
under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
REPRESENTATIONS OF ANY KIND, either express or implied. See the License for the
specific language governing permissions and limitations under the License.
-}
{-# LANGUAGE QuasiQuotes #-}
module TransformsSpec (main, spec) where

import Control.Monad (forM_)
import Test.Hspec
--import Test.HUnit
--import Text.Pretty.Simple (pPrintLightBg)

import Misc
import NameGen
import Number
import AST
import Transforms

main :: IO ()
main = hspec spec

spec :: Spec
spec = do
  test_xformFctDef
  regression_test_simplifyVec
  regression_test_simplifyDiag
  test_simplifyDiag

test_xformFctDef :: Spec
test_xformFctDef =
  describe "xformFctDef" $ do
    let xform :: ExprT -> NameGen ExprT
        xform e = do
          v <- newName "bar"
          return $ Apply (typeOf e) "foo" [Var IType v, e]
    let parms =
          [ "n" .-> typeSB IType [] (lobound $ litI 0)
          , "a" .-> typeSB VecType
                      [Var IType "n"] (bounds (litR 1.0) (litR 10.0))
          ]
    let parms1 =
          [ "n" .-> typeSB IType []
                    (lobound $ Apply IType "foo" [Var IType "bar_0", litI 0])
          , "a" .-> typeSB VecType
                    [Apply IType "foo" [Var IType "bar_1", Var IType "n"]]
                    (bounds (Apply RType "foo" [Var IType "bar_2", litR 1.0])
                            (Apply RType "foo" [Var IType "bar_3", litR 10.0]))
          ]
    let body =
          Apply TSDType "somefun" [Var IType "n", Var VecType "a"]
    let body1 =
          Apply TSDType "foo" [Var IType "bar_4", body]
    let fd = FctDef
             { defName = "fname"
             , defParms = parms
             , defRetType = TSDType
             , defBody = body
             }
    let fd1 = fd{ defParms = parms1, defBody = body1 }
    it "xforms params and body" $
      xformFctDef xform fd `shouldBe` fd1

test_simplifyDiag :: Spec
test_simplifyDiag =
  describe "simplifyDiag" $ do
    it "handles diag(diag(scalar * vec), diag(vec(scalar, scalar)))" $ do
      let vec1 = Apply VecType "*" [Var RType "c", Var VecType "v"]
          vec2 = Apply VecType "vec" [Var RType "a", Var RType "b"]
          arg1 = Apply MatType "diag" [ vec1 ]
          arg2 = Apply MatType "diag" [ vec2 ]
          expected = Apply MatType "diag" [Apply VecType "vec" [vec1, vec2]]
      simplifyDiag [arg1, arg2] `shouldBe` expected

regression_test_simplifyVec :: Spec
regression_test_simplifyVec =
  describe "simplifyVec (regr)" $ do
    it "passes regression tests" $ do
      length regr_cases_vec `shouldBe` length regr_results_vec
      forM_ (zip regr_cases_vec regr_results_vec) $ \(x,y) -> do
        x `shouldBe` y

regression_test_simplifyDiag :: Spec
regression_test_simplifyDiag =
  describe "simplifyDiag (regr)" $ do
    it "passes regression tests" $ do
      length regr_cases_diag `shouldBe` length regr_results_diag
      forM_ (zip regr_cases_diag regr_results_diag) $ \(x,y) -> do
        x `shouldBe` y

regr_cases_vec :: [ExprT]
regr_cases_vec =
  [ simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Var RType "mu_a",Apply VecType "vec" []]
  , simplifyVec [Var RType "mu_a"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [],Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_q"],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]
  , simplifyVec [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"],Apply VecType "vec" [],Apply VecType "vec" [Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"],Apply VecType "vec" [Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_a"],Var VecType "csigma2s_0"]
  , simplifyVec [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]]
  , simplifyVec [Var RType "phi",Lit RType (RealVal 1.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0)],Apply VecType "vec" [Var RType "mu"]]
  , simplifyVec [Lit RType (RealVal 0.0),Var RType "mu"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]]
  , simplifyVec [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]]
  , simplifyVec [Var RType "phi",Lit RType (RealVal 1.0)]
  , simplifyVec [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0)],Apply VecType "vec" [Var RType "mu"]]
  , simplifyVec [Lit RType (RealVal 0.0),Var RType "mu"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Var RType "mu_a",Apply VecType "vec" []]
  , simplifyVec [Var RType "mu_a"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [Lit RType (RealVal 0.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]
  , simplifyVec [Var RType "mu_a",Apply VecType "vec" [Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"],Apply VecType "vec" [Lit RType (RealVal 0.0)]]
  , simplifyVec [Var RType "mu_a",Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)],Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)],Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]]
  , simplifyVec [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)],Apply VecType "vec" [Lit RType (RealVal 0.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)],Apply VecType "vec" [Lit RType (RealVal 0.0)]]
  , simplifyVec [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Var RType "mu_d",Apply VecType "vec" []]
  , simplifyVec [Var RType "mu_d"]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_d"],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_d"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0)],Apply VecType "vec" [Lit RType (RealVal 0.0)]]
  , simplifyVec [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]
  , simplifyVec [Var RType "mu_a",Apply VecType "vec" [Var RType "mu_d"]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a"],Apply VecType "vec" [Var RType "mu_d"]]
  , simplifyVec [Var RType "mu_a",Var RType "mu_d"]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]]
  , simplifyVec [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"],Apply VecType "vec" []]
  , simplifyVec [Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]]
  , simplifyVec [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]
  ]

regr_results_vec :: [ExprT]
regr_results_vec =
  [ Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]
  , Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]
  , Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Var RType "mu"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Var RType "mu_a"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Lit RType (RealVal 0.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_d"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0)]
  , Apply VecType "vec" [Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_d"]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Lit RType (RealVal 1.0),Lit RType (RealVal 0.0)]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Var RType "mu_a",Var RType "mu_d"]
  , Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]
  ]

regr_cases_diag :: [ExprT]
regr_cases_diag =
  [ simplifyDiag [Apply RType "square" [Var RType "sigma_q"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_a"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]]]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" [],Apply MatType "diag" [Apply (RArrType 3) "*" [Apply RType "sqrt" [Apply RType "-" [Lit RType (RealVal 1.0),Var RType "rhoSqr_0"]],Apply (RArrType 3) "{}" [Apply MatType "mat22" [Lit RType (RealVal 0.6234898018587336),Lit RType (RealVal (-0.7818314824680297)),Lit RType (RealVal 0.7818314824680297),Lit RType (RealVal 0.6234898018587336)],Apply MatType "mat22" [Lit RType (RealVal (-0.22252093395631434)),Lit RType (RealVal (-0.9749279121818236)),Lit RType (RealVal 0.9749279121818236),Lit RType (RealVal (-0.22252093395631434))],Apply MatType "mat22" [Lit RType (RealVal (-0.900968867902419)),Lit RType (RealVal (-0.43388373911755823)),Lit RType (RealVal 0.43388373911755823),Lit RType (RealVal (-0.900968867902419))]]]]]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" [Apply (RArrType 3) "*" [Apply RType "sqrt" [Apply RType "-" [Lit RType (RealVal 1.0),Var RType "rhoSqr_0"]],Apply (RArrType 3) "{}" [Apply MatType "mat22" [Lit RType (RealVal 0.6234898018587336),Lit RType (RealVal (-0.7818314824680297)),Lit RType (RealVal 0.7818314824680297),Lit RType (RealVal 0.6234898018587336)],Apply MatType "mat22" [Lit RType (RealVal (-0.22252093395631434)),Lit RType (RealVal (-0.9749279121818236)),Lit RType (RealVal 0.9749279121818236),Lit RType (RealVal (-0.22252093395631434))],Apply MatType "mat22" [Lit RType (RealVal (-0.900968867902419)),Lit RType (RealVal (-0.43388373911755823)),Lit RType (RealVal 0.43388373911755823),Lit RType (RealVal (-0.900968867902419))]]]]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]],Apply MatType "diag" [],Apply MatType "diag" [Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]],Apply MatType "diag" [Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , simplifyDiag [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "diag" [],Apply MatType "diag" [Var VecType "csigma2s_0"]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "diag" [Var VecType "csigma2s_0"]]
  , simplifyDiag [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]]
  , simplifyDiag [Var RType "phi"]
  , simplifyDiag [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma"]]
  , simplifyDiag [Lit RType (RealVal 1.0)]
  , simplifyDiag [Lit RType (RealVal 0.0)]
  , simplifyDiag [Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]
  , simplifyDiag [Apply MatType "mat11" [Var RType "phi"],Apply MatType "mat11" [Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]]],Apply MatType "mat11" [Lit RType (RealVal 0.0)]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma"]],Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]]
  , simplifyDiag [Var RType "phi"]
  , simplifyDiag [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_a"]]
  , simplifyDiag [Lit RType (RealVal 1.0)]
  , simplifyDiag [Lit RType (RealVal 0.0)]
  , simplifyDiag [Apply RType "square" [Var RType "sigmamu_a"]]
  , simplifyDiag [Apply MatType "mat11" [Var RType "phi"],Apply MatType "mat11" [Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]]],Apply MatType "mat11" [Lit RType (RealVal 0.0)]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigmamu_a"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_q"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_a"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]]]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]]
  , simplifyDiag [Var RType "phi_d"]
  , simplifyDiag [Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_d"]]
  , simplifyDiag [Lit RType (RealVal 0.0),Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , simplifyDiag [Apply VecType "vec" [Lit RType (RealVal 0.0)],Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , simplifyDiag [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_a"],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Var RType "phi_b"]
  , simplifyDiag [Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_b"]]
  , simplifyDiag [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Var RType "phi_d"],Apply MatType "mat11" [Var RType "phi_b"],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Var RType "phi_d"],Apply MatType "mat11" [Var RType "phi_b"]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]],Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]],Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]]
  , simplifyDiag [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_b"]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_b"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_qd"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qd"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qd"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_d"],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_d"]],Apply MatType "diag" []]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_qa"],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , simplifyDiag [Apply RType "square" [Var RType "sigma_a"],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , simplifyDiag [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]],Apply MatType "diag" []]
  , simplifyDiag [Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]]
  ]

regr_results_diag :: [ExprT]
regr_results_diag =
  [ Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "diag" [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" [Apply (RArrType 3) "*" [Apply RType "sqrt" [Apply RType "-" [Lit RType (RealVal 1.0),Var RType "rhoSqr_0"]],Apply (RArrType 3) "{}" [Apply MatType "mat22" [Lit RType (RealVal 0.6234898018587336),Lit RType (RealVal (-0.7818314824680297)),Lit RType (RealVal 0.7818314824680297),Lit RType (RealVal 0.6234898018587336)],Apply MatType "mat22" [Lit RType (RealVal (-0.22252093395631434)),Lit RType (RealVal (-0.9749279121818236)),Lit RType (RealVal 0.9749279121818236),Lit RType (RealVal (-0.22252093395631434))],Apply MatType "mat22" [Lit RType (RealVal (-0.900968867902419)),Lit RType (RealVal (-0.43388373911755823)),Lit RType (RealVal 0.43388373911755823),Lit RType (RealVal (-0.900968867902419))]]]]]
  , Apply MatType "diag" [Apply MatType "mat11" [Lit RType (RealVal 1.0)],Apply MatType "diag" [Apply (RArrType 3) "*" [Apply RType "sqrt" [Apply RType "-" [Lit RType (RealVal 1.0),Var RType "rhoSqr_0"]],Apply (RArrType 3) "{}" [Apply MatType "mat22" [Lit RType (RealVal 0.6234898018587336),Lit RType (RealVal (-0.7818314824680297)),Lit RType (RealVal 0.7818314824680297),Lit RType (RealVal 0.6234898018587336)],Apply MatType "mat22" [Lit RType (RealVal (-0.22252093395631434)),Lit RType (RealVal (-0.9749279121818236)),Lit RType (RealVal 0.9749279121818236),Lit RType (RealVal (-0.22252093395631434))],Apply MatType "mat22" [Lit RType (RealVal (-0.900968867902419)),Lit RType (RealVal (-0.43388373911755823)),Lit RType (RealVal 0.43388373911755823),Lit RType (RealVal (-0.900968867902419))]]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_q"]],Apply VecType "*" [Var RType "rhoSqr_0",Var VecType "csigma2s_0"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"]],Var VecType "csigma2s_0"]]
  , Apply MatType "mat11" [Var RType "phi"]
  , Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma"]]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Lit RType (RealVal 0.0)]
  , Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma"],Apply RType "square" [Apply RType "*" [Lit RType (RealVal 1.0e-2),Var RType "sigma"]]]]
  , Apply MatType "mat11" [Var RType "phi"]
  , Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Lit RType (RealVal 0.0)]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigmamu_a"]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Var RType "phi",Lit RType (RealVal 1.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Apply RType "*" [Var RType "rho",Var RType "sigma_a"]],Lit RType (RealVal 0.0)]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigmamu_a"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_q"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_a"]]
  , Apply MatType "mat11" [Var RType "phi_d"]
  , Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "mat11" [Var RType "phi_b"]
  , Apply MatType "mat11" [Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_b"]]
  , Apply MatType "diag" [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Var RType "phi_d"],Apply MatType "mat11" [Var RType "phi_b"]]
  , Apply MatType "diag" [Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Var RType "phi_d"],Apply MatType "mat11" [Var RType "phi_b"]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Lit RType (RealVal 0.0),Apply RType "square" [Apply RType "*" [Var RType "rho_d",Var RType "sigma_d"]],Apply RType "square" [Apply RType "*" [Var RType "rho_b",Var RType "sigma_b"]]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"],Apply RType "square" [Var RType "sigma_b"]]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Lit RType (RealVal 1.0)]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_qd"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "mat11" [Apply RType "square" [Var RType "sigma_d"]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply MatType "mat22" [Lit RType (RealVal 1.0),Lit RType (RealVal 1.0),Lit RType (RealVal 0.0),Lit RType (RealVal 1.0)]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_qa"],Apply RType "square" [Var RType "sigma_qd"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  , Apply MatType "diag" [Apply VecType "vec" [Apply RType "square" [Var RType "sigma_a"],Apply RType "square" [Var RType "sigma_d"]]]
  ]
